server:
  port: 8090

spring:
  application:
    name: gestaoaluno
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestaoalunodb
    username: postgres
    password: postgre1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
